
import "./globals.css";
import { Providers } from "@/redux/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
          <Providers>{children}</Providers>
      </body>
    </html>
  );
}
